README.md
pkg/plugins/builtin/http/README.md
pkg/plugins/builtin/http/http.go

Implement HTTP plugin missing options

---

README.md
engine/engine.go
engine/engine_test.go
engine/step/condition.go
engine/templates_tests/simple.yaml
engine/values/values.go
models/resolution/resolution.go

accessor for step error in templating values

---

README.md
pkg/plugins/builtin/builtin.go
pkg/plugins/builtin/email/README.md
pkg/plugins/builtin/email/email.go

Create email plugin

---

hack/generate-install-script.sh

Signed-off-by: Thomas SOËTE <github@alkorin.fr>

Get rid of weird and not posix compliant sed

---

pkg/plugins/builtin/http/README.md
pkg/plugins/builtin/http/http.go

Replace the unspported fields types by strings

Fix http-plugin config format

---

api/handler/resolution.go
api/middleware.go
cmd/utask/version.go
engine/collector_retry.go
engine/step/step.go
engine/values/values.go
pkg/auth/auth.go
pkg/jsonschema/jsonschema.go
pkg/plugins/builtin/ssh/ssh.go
pkg/plugins/plugins.go

Related to https://github.com/avelino/awesome-go/pull/2829

Improve goreport

---

go.mod
go.sum

fix: delete dirty replace in go.mod

---

engine/engine_test.go

fixup! test: Improve code coverage (#37) 🎉

---

engine/engine_test.go

Clear ineffassign

---

pkg/plugins/builtin/notify/README.md

Signed-off-by: Chris Camel <9574336+ccamel@users.noreply.github.com>
Minor PR that fixes typo on documentation.
N/A.
N/A
N/A
N/A

docs: Fix incorrect action type value in example

---

api/api_test.go

fix: CI go test checker

---

.travis.yml

Improve way to install Goreleaser in CI

---

Makefile

fix: release process

---

pkg/plugins/builtin/http/README.md
pkg/plugins/builtin/http/http.go

Be able to make http call to api like Gerrit
Cannot communicate with service that add prefix in their response
Define a prefix to remove
No

feat(plugin): add magic prefix that has to be removed from api response (like gerrit for example))

---

.goreleaser.yml
.travis.yml
Makefile

clear: release process 🍷

---

go.sum
pkg/plugins/builtin/http/README.md
pkg/plugins/builtin/http/http.go
pkg/plugins/builtin/http/http_test.go
pkg/plugins/builtin/httputil/httputil.go
pkg/plugins/builtin/httputil/httputil_test.go
pkg/plugins/taskplugin/metadata.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/modules.txt

**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
HTTP Plugin new features and unit tests
**What is the current behavior?** (You can also link to an open issue here)
**What is the new behavior (if this is a feature change)?**
Improvements on http plugin:
* bearer token authentication
* returns Cookies in metadata
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
The `auth_basic` configuration is replaced by `auth`. If think it's more elegant, but we can discuss about it if you prefer to keep it.
**Other information**:

feat: http plugin improments

---

pkg/plugins/builtin/subtask/subtask.go

fix: subtask: templating issue when creating subtask in foreach loop #66

---

engine/templates_tests/execScript.yaml
pkg/plugins/builtin/script/README.md
pkg/plugins/builtin/script/script.go

Bug fix about the script execution and relative file path
Changed the `file` field in `file_path` bc it's more relevant.

Fix relative file path 🐞 + rename file field

---

models/tasktemplate/fromdir.go

fix: template: Need to normalize template before updating

---

api/server.go

We should not verify for user authentication/authorization on
dashboard/editor static files.

fix: dashboard: remove authentication requirements for serving static assets

---

models/tasktemplate/fromdir.go
pkg/plugins/builtin/subtask/subtask.go
pkg/templateimport/templateimport.go

fix: templates: Multiple templates import no longer breaks when depends of each others in sub-task pluggin

---

pkg/plugins/builtin/http/http.go
pkg/plugins/builtin/http/http_test.go

Bug fix
HTTP plugin: headers are key/value pairs
Follow_redirect is mandatory
HTTP plugin: headers are name/value pairs
Follow_redirect is optional

HTTP plugin fixes from 1.3.0 regressions

---

engine/engine.go

Fix bug
Steps done count can be inconsistent in case of foreach/children
Consistent done count

Engine: fix consistent steps done count

---

ui/dashboard/src/app/@components/stepslist/stepslist.component.ts
ui/dashboard/src/app/@components/stepslist/stepslist.html
ui/dashboard/src/app/@components/stepsviewer/stepsviewer.component.ts
ui/dashboard/src/app/@components/stepsviewer/stepsviewer.html
ui/dashboard/src/app/@routes/home/home.component.ts
ui/dashboard/src/app/@routes/home/home.html
ui/dashboard/src/app/@routes/task/task.component.ts
ui/dashboard/src/app/@routes/task/task.html
ui/dashboard/src/app/@services/graph.service.ts
ui/dashboard/src/styles.sass

fix: ui/dashboard

---

config/README.md
db/init.go
utask.go

Configuration management (feature)
The database info is expected in the "database" config entry
The database info location can be configured (utask-cfg.database_config.config_name)

Configurable database config name

---

README.md
config/README.md

Update README with precisions for templating functions + JavaScript eval

---

api/api_test.go
api/handler/batch.go
api/handler/task.go
engine/engine.go
engine/engine_test.go
engine/step/step.go
engine/step/util.go
models/task/task.go
models/tasktemplate/fromdir_test.go
models/tasktemplate/template.go
pkg/plugins/builtin/builtin.go
pkg/plugins/builtin/http/http_test.go
pkg/plugins/builtin/subtask/subtask.go
pkg/plugins/builtin/tag/README.md
pkg/plugins/builtin/tag/tag.go
pkg/plugins/plugins.go
pkg/plugins/taskplugin/taskplugin.go
pkg/taskutils/taskutils.go
sql/migrations/002_tags.sql
sql/schema.sql

feat: add tags to task

---

README.md
engine/engine_test.go
engine/templates_tests/variables.yaml
engine/values/values.go
models/tasktemplate/fromdir_test.go
models/tasktemplate/template.go
models/tasktemplate/templates_errors_tests/error-variables.yaml

Adding templating feature for tasktemplate variables.
Added some validation on Variables for templates, making sure that all
properties are correctly defined.

feat: variables value can be templated

---

sql/migrations/002_tags.sql
sql/migrations/003_misc_indexes_and_constraints.sql
sql/schema.sql

GIN indexes have reputation to increase performance on JSONB.

fix: sql: Switching task JSONB indexes to GIN

---

.github/PULL_REQUEST_TEMPLATE.md

Those checkboxes are the worst.

github: Removing check-boxes from pull-request templates

---

CHANGELOG.md

Changelog for breaking changes in 1.5.0

Changelog for 1.5.0

---

Dockerfile

Changing build version of Golang
No changes expected, better stability given Golang 1.14 changelog
Note:
```
The text/template package now correctly reports errors when a parenthesized argument is used as a function. This most commonly shows up in erroneous cases like {{if (eq .F "a") or (eq .F "b")}}. This should be written as {{if or (eq .F "a") (eq .F "b")}}. The erroneous case never worked as expected, and will now be reported with an error can't give argument to non-function. 
```
https://golang.org/doc/go1.14
* **Does this PR introduce a breaking change?** …

misc: building utask using Golang 1.14

---

models/tasktemplate/fromdir.go

Fix error messages when loading templates
Doesnt include template name
Includes it

Fix template load messages (template name)

---

engine/engine.go

When a task fails to validate requirements of a template, task is set to
BLOCKED state, whereas resolution stayed in RUNNING state, making it
impossible for admins to manage the task anymore.
Switching resolution to a CRASHED state will allow manipulation by
admins.
Fixing a bug
Task that failed to validate a template was in BLOCKED state with resolution in RUNNING state, couldn't be used in the API anymore.
Resolution in CRASHED state
No
* …

fix: engine: tasks could stay in inconsistent state when fails to validate templates

---

README.md

README content
New License section in the readme, detailing the use of the Gopher image and Swagger UI.

README: section License

---

pkg/plugins/builtin/subtask/README.md
pkg/plugins/builtin/subtask/subtask.go

Typo
`requesterUsername` -> `requester_username`
`resolverUsername` -> `resolver_username`
Yes, but never released yet so, it's OK.

subtask: new result should be formatted with underscores

---

pkg/plugins/builtin/echo/README.md
pkg/plugins/builtin/echo/echo.go
pkg/utils/utils.go

A feature to unmarshal echo content before returning
We cannot unmarshal
We can unmarshal
No

feature: can unmarshal echo output before returning

---

api/handler/resolution.go
api/handler/task.go
engine/input/input.go
engine/step/condition.go
engine/step/step.go
models/task/task.go
models/tasktemplate/template.go
pkg/utils/utils.go

fix: error messages for bad requests

---

pkg/plugins/plugins.go

Bug fix
Regarding how an init plugin is declared, Golang, sometimes, seems to allow a type cast to `InitializerPlugin`.
In some cases, like #149, type cast to interface is not allowed because plugin is referenced as pointer.
All symbol loaded from `plugin.Lookup` seems to returned pointer value, so we will dereference before the explicit type-cast.
No
Fixes #149

plugin: retrieve non-pointer interface before casting into plugin Interface

---

examples/README.md
examples/plugins/init/auth.go

Documentation with code example
Adding an example source code on how to develop a plugin. This init
plugin override the built-in authentication system with a custom
authenticator, relying on SHA256 and remote IP address just for the
example.
No
Closes #150

docs: add a plugin example source code

---

api/handler/batch.go
api/handler/task.go
engine/engine.go
engine/engine_test.go
engine/templates_tests/subtask.yaml
models/tasktemplate/template.go
pkg/constants/constants.go
pkg/plugins/builtin/subtask/subtask.go
pkg/plugins/builtin/tag/tag.go
pkg/utils/utils.go

Feature
In case we have a template running some subtasks, we should wake up the
parent task after one of the subtasks has reached completion
No
No

subtask: auto-resume parent task when the subtask finished running

---

ui/dashboard/package-lock.json
ui/dashboard/package.json
ui/dashboard/src/app/@routes/new/new.component.ts
ui/dashboard/src/app/@routes/new/new.html
ui/dashboard/src/app/@routes/task/task.component.ts
ui/dashboard/src/app/@routes/task/task.html
ui/dashboard/src/app/app.module.ts

Multiline for new task

---

hack/Dockerfile-child
hack/generate-install-script.sh

Bug fix
functions folder is not integrated into newly project `Dockerfile`'s 
functions folder is integrated into newly project `Dockerfile`'s 
No

fix: Add functions/ folder to install-script

---

docker-compose.yaml
hack/interactive.sh
hack/test-docker.sh
hack/test.sh

Bug fix
Development workflow was not working anymore, it's now fixed, with a smaller docker image for postgres.

misc: repair development workflow

---

api/handler/task.go

Bug fix
When a subtask is spawned, some default tags are assigned to the subtask, and they are only read-only.
We can't edit the task anymore without removing the read-only tag, which is annoying.
Handle correctly the task edition without touching the read-only tags.
No

fix: unable to edit task that have read-only tags

---

hack/template-schema.json

We were missing some new fields in the json-schema template specification, here are the additions.
No

chore: update json-schema template specification

---

pkg/plugins/builtin/http/README.md
pkg/plugins/builtin/http/http.go
pkg/plugins/builtin/http/http_test.go
pkg/plugins/builtin/httputil/httputil.go

Feature
Add configuration field to enable Mutual TLS client authentication.

http: add mTLS for client authentication

---

README.md
config/README.md
models/task/task.go
pkg/notify/init/init.go
pkg/notify/messages.go
pkg/notify/webhook/webhook.go
utask.go

Feature
Added a webhook provider for the notification system.
Added also more fields to be sent with the notification.
No

feat(notification): add Webhook as notification system

---

api/handler/task.go
models/task/task.go

Feature
Adding a filter on `GET /task` to filter on the template_name.
No

api: task: add filter on template

---

ui/dashboard/package-lock.json
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.html
ui/dashboard/projects/utask-lib/src/lib/@services/api.service.ts

Feature new filter in tasks list on template name.

feat(ui): add template filter for tasks

---

README.md
engine/engine.go
engine/engine_test.go
engine/step/step.go
engine/templates_tests/foreach.yaml

Each elements of a foreach loop are run in parallel.
`foreach_strategy` control the fact that elements will be run
sequentially or in parallel.
Closes #197

foreach: add `foreach_strategy` property to ensure sequence between foreach elements

---

ui/dashboard/Makefile
ui/dashboard/extra-webpack.config.js
ui/dashboard/package-lock.json
ui/dashboard/package.json
ui/dashboard/projects/utask-lib/package.json
ui/dashboard/projects/utask-lib/src/lib/@components/inputs-form/inputs-form.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/inputs-form/inputs-form.html
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.sass
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.sass
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/template-details/template-details.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/template-details/template-details.html
ui/dashboard/projects/utask-lib/src/lib/@models/task.model.ts
ui/dashboard/projects/utask-lib/src/lib/@pipes/fromNow.pipe.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/function/function.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/function/function.html
ui/dashboard/projects/utask-lib/src/lib/@routes/function/function.sass
ui/dashboard/projects/utask-lib/src/lib/@routes/functions/functions.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/functions/functions.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.html
ui/dashboard/projects/utask-lib/src/lib/@routes/template/template.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/templates/templates.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/templates/templates.html
ui/dashboard/projects/utask-lib/src/lib/@services/api.service.ts
ui/dashboard/projects/utask-lib/src/lib/@services/workflow.service.ts
ui/dashboard/projects/utask-lib/src/lib/utask-lib.routing.module.ts

Fix override params for time pipe component.
Orange color for step TO_RETRY state and label retrying for execution with state ERROR.
Dedicate function page.
Get yaml values for template and function from api.
Fix packaging lib for dev purpose.
Update some deps and package-lock using nodejs 14.
Default values for template form and fix null value fox checkbox.

fix(ui): dedicate function page, avoid yaml/json conversion, other fixes

---

ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.sass
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.sass
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.component.ts
ui/dashboard/projects/utask-lib/src/lib/@services/workflow.service.ts
ui/editor/src/app/components/stepsviewer.html
ui/editor/src/app/services/workflowhelper.service.ts

* Use a darker green to display DONE steps
* Allow to disable bulk actions on tasks list
* Allow to customize tasks url
* DONE steps are displayed with a light green and white text - difficult to read
* bulk actions cannot be disabled while integrating component in an external app
* current implementation forces to have "/task/" in task URL
* DONE steps are displayed with a darker green (same of "DONE" task)
* bulk actions can be disabled (enabled by default)
* URL of task can be fully customized
* **Does this PR introduce a breaking change?** (What changes might …

Utask lib features

---

ui/dashboard/projects/utask-lib/src/lib/@components/inputs-form/inputs-form.html
ui/dashboard/projects/utask-lib/src/lib/@routes/new/new.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass

Dashboard UI: Update the new task form to be vertical
Dashboard UI: Update the new task form labels to use input description instead of input name
Dashboard UI: Increase the graph width in the task page details

Sma UI form task

---

ui/dashboard/projects/utask-lib/src/lib/@components/editor/editor.html
ui/dashboard/projects/utask-lib/src/lib/@components/input-tags/input-tags.html
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.html
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.html
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.sass
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.html
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.sass
ui/dashboard/projects/utask-lib/src/lib/@directives/ns-auto-height-table.directive.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/new/new.html
ui/dashboard/projects/utask-lib/src/lib/@routes/stats/stats.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass
ui/dashboard/src/app/@routes/base/base.html
ui/dashboard/src/app/@routes/not-found/not-found.html
ui/editor/src/app/services/workflowhelper.service.ts

Style for auto refresh button.
Style for task form.

feat(ui): fix some style issues

---

README.md
engine/engine.go
engine/engine_test.go
engine/templates_tests/stepCondition.yaml

Feature
Added the state of the iteration inside the children map, to retrieve a
custom state, in case other dependencies need to handle this
differently.
No

feat(foreach): include iteration state inside the children map

---

ui/dashboard/projects/utask-lib/src/lib/@components/input-editor/input-editor.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/input-editor/input-editor.html
ui/dashboard/projects/utask-lib/src/lib/@components/input-editor/input-editor.sass
ui/dashboard/projects/utask-lib/src/lib/@modals/modal-api-yaml-edit/modal-api-yaml-edit.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/new/new.component.ts
ui/dashboard/projects/utask-lib/src/lib/@services/request.service.ts
ui/dashboard/projects/utask-lib/src/lib/utask-lib.module.ts

fix(ui): editor for request and resolution, js error template no inputs

---

ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.component.ts

Signed-off-by: richardlt <richard.le.terrier@gmail.com>

fix(ui): tasks list detect params change

---

ui/dashboard/projects/utask-lib/src/lib/@routes/new/new.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html

fix(ui): style for task page button, search for template list

---

engine/engine_test.go
engine/step/step.go

Bug fix
Some tricky case on step output templating weren't catched, and caused
the step to result in DONE, instead of BLOCKED_FATAL
Diff is really small with ignore whitespace to 1.
No
Fixes #230.

fix: engine: invalid templating wasn't catched all the time

---

api/handler/batch.go
api/handler/common.go
api/handler/task.go
api/yamlbinding.go
engine/collector_garbage.go
engine/collector_instance.go
engine/engine.go
engine/functions/functions.go
engine/step/apply.go
engine/step/apply_test.go
engine/step/step.go
engine/values/values.go
models/runnerinstance/instance.go
models/task/task.go
pkg/now/syncnow.go
pkg/plugins/plugins.go
pkg/templateimport/templateimport.go
pkg/utils/utils.go
utask.go

Fix
Some issues were raised by golangci-lint, inducing errors in the task processing, or error behaviour that weren't reported in the logs.
It's now fixed.
Fixed some typos and removed dead code also.
No

fix(): various fixes following golangci-lint reports

---

api/handler/task.go
models/task/task.go

Feature
Regular users can't list all their tasks (requested and resolved)
Regular users can now list all their tasks.
No

feat(api): list all tasks related to a regular user

---

ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.component.ts
ui/dashboard/projects/utask-lib/src/lib/@models/task.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.component.ts

Signed-off-by: richardlt <richard.le.terrier@gmail.com>

feat(ui): use new all tasks filter for both admin and non admin

---

.golangci.yml
api/handler/batch.go
api/handler/comment.go
api/handler/function.go
api/handler/resolution.go
api/handler/task.go
api/handler/template.go
api/middleware.go
api/server.go
cmd/utask/root.go
engine/collector_autorun.go
engine/collector_retry.go
engine/engine.go
go.mod
go.sum
pkg/auth/auth.go
pkg/metadata/metadata.go
pkg/taskutils/taskutils.go
utask.go

Signed-off-by: William Poussier <william.poussier@ovhcloud.com>
Refactor of the error logs middleware.
Only errors with a few fields are logged.
This logs more metadata, such as the action name, user, ...
No.

feat: improve audit logs middleware

---

pkg/plugins/builtin/email/email.go

Signed-off-by: Thomas SOËTE <thomas.github@soete.org>

fix(): email port is only 16bits

---

pkg/plugins/builtin/scriptutil/scriptutil.go

Signed-off-by: Thomas SOËTE <thomas.github@soete.org>

fix(): Useless assignment to local variable

---

README.md
engine/engine_test.go
engine/step/condition/condition.go
engine/templates_tests/stepCondition.yaml

Feature
Introduces a new operator `NOTREGEXP` to be used in conditions and make sure a value doesn't match a given regexp
No

operator: introduces NOTREGEXP operator

---

ui/dashboard/projects/utask-lib/src/lib/@components/box/box.component.ts

Signed-off-by: Thomas SOËTE <thomas.github@soete.org>

fix(): check for fontColor

---

ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.html

fix(ui): remove both option from task type filter

---

engine/step/step.go
ui/dashboard/package-lock.json
ui/dashboard/package.json
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.html
ui/dashboard/projects/utask-lib/src/lib/@modals/modal-edit-resolution-step-state/modal-edit-resolution-step-state.component.ts
ui/dashboard/projects/utask-lib/src/lib/@modals/modal-edit-resolution-step-state/modal-edit-resolution-step-state.html
ui/dashboard/projects/utask-lib/src/lib/@models/step.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/lib/@services/api.service.ts
ui/dashboard/projects/utask-lib/src/lib/utask-lib.module.ts
ui/editor/package-lock.json
ui/editor/package.json
ui/editor/src/app/services/workflowhelper.service.ts

feature(UI): Enable to edit step in yaml
feature(UI): Enable to edit step state

feat(ui): Edit step

---

pkg/metadata/metadata.go

Bug fix
Correctly cast the action_metadata map to propagate action metadata to audit logs
NO

fix: audit-logs: cast correctly the metadata map

---

ui/dashboard/package-lock.json
ui/dashboard/projects/utask-lib/src/lib/@services/request.service.ts

Bug fix on dashboard UI
Tasks can't be resolve by non-admin users
Tasks can be resolve by non-admin users if there are present in resolver list

fix(ui/dashboard): Determine if a task a resolvable

---

sql/schema.sql

Small bug fix on global schema.

Fix DROP TABLE in schema.sql

---

README.md
hack/function-schema.json

Feature
Add a JSON-schema validation file for functions
No

feat: add JSON-schema validation for functions

---

go.mod
go.sum

Bump of dependencies
Correction of vulnerabilities in dependencies
No

fix: bump dependencies to integrate latest vulnerabilities reports

---

api/handler/task.go
engine/engine.go
models/task/task.go

Feature
A subtask that is WONTFIX won't wake up the parent task, hence, the parent task can sleep for one hour before getting resolved.
Parent task is now waked up
No
ping @Alkorin

feat: auto-resolve parents task when sub-task is WONTFIX

---

ui/dashboard/package-lock.json
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html

feature start over on dashboard UI

implement start over UI

---

ui/dashboard/projects/utask-lib/src/lib/@components/box/box.html
ui/dashboard/projects/utask-lib/src/lib/@components/box/box.sass
ui/dashboard/projects/utask-lib/src/lib/@components/error-message/error-message.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.html
ui/dashboard/projects/utask-lib/src/lib/@components/steps-viewer/steps-viewer.sass
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.html
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.sass
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/public-api.ts

fix: display HTTP error info

---

engine/engine.go
engine/engine_test.go
engine/step/step.go
models/resolution/resolution.go
models/task/task.go
pkg/plugins/builtin/subtask/subtask.go
ui/dashboard/angular.json
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/step-node/step-node.sass
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.html
ui/dashboard/projects/utask-lib/src/lib/@components/task-status/task-status.sass
ui/dashboard/projects/utask-lib/src/lib/@models/task.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/stats/stats.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.html
ui/dashboard/projects/utask-lib/src/lib/@services/workflow.service.ts

Improve subtasks management.
If a step waiting for a subtask kept in TODO has less "try" than the max tries, the step state is TO_RETRY and resolution running. If step is over, then resolution is BLOCKED.
Resolution will always be WAITING if there is no other failed steps.
No breaking change.

feat: add waiting state for subtasks steps

---

ui/dashboard/projects/utask-lib/src/lib/@components/stepslist/stepslist.component.ts
ui/dashboard/projects/utask-lib/src/lib/@components/tasks-list/tasks-list.component.ts

use UTaskLibOptions.uiBaseUrl in TasksListComponentOptions if required.

fix(utask-lib): use UTaskLibOptions uiBaseUrl if provided

---

engine/values/values.go

Signed-off-by: Thomas Bétrancourt <thomas@betrancourt.net>

chore: increase javascript execution timeout

---

.gitignore
vscode/CHANGELOG.md
vscode/README.md

Signed-off-by: Thomas Bétrancourt <thomas@betrancourt.net>

chore: fix the doc and the gitignore

---

api/handler/task.go

Swagger update.
The `type` field on Swagger UI is an input.
The `type` field on Swagger UI is a select with the allowed values (`own,resolvable,all`).
No breaking change.

feat(task): improve Swagger for task listing

---

engine/step/step.go

Bug fix.
When a pre-hook fails, the step execution continues as if the pre-hook was executed correctly. In addition, the `stepChan` will receive the same step twice, because the pre-hook error handling sends the step into `stepChan` and the step execution also sends it.
To reproduce the case, you can use the example [1] (see below). The two first steps (`getTime` & `sayFoo`) will be executed, but the `sayFoo` will be fully executed and received twice by `stepChan`. Consequence, the `getTime` step is no longer tracked by the engine.
The action of the step will be …

fix(step): stop the step execution if the pre-hook has failed

---

docker-compose.yaml

Signed-off-by: liys87x <liyasong1987x@gmail.com>
Bug fix
#362 

fix: add backup-config to docker-compose.yaml

---

docker-compose.yaml

Chore
The postgres version 9.6 is used for development. This version is deprecated.
The postgres version 14 is used for development.
No

chore: use postgres:14-alpine

---

Dockerfile
go.mod
go.sum

Chore
µTask being built with Go 1.19
No

chore(): bumping to Go 1.19

---

hack/test-docker.sh

chore
not possible to use a docker network during tests in docker
allow to use an existing docker network during tests and allow to override the db schema file path

chore: allow to override db schema and docker network in tests

---

engine/engine_test.go
engine/templates_tests/execScriptWithEnvironment.yaml
hack/template-schema.json
pkg/plugins/builtin/script/README.md
pkg/plugins/builtin/script/script.go

feature
not possible to pass custom environment variables to scripts
allow to pass custom variables to scripts through the `environment` parameterr
Closes #226

feat(script): allow to pass custom environment variables (#226)

---

engine/engine_test.go
engine/templates_tests/subtask.yaml
hack/template-schema.json
pkg/plugins/builtin/subtask/README.md
pkg/plugins/builtin/subtask/subtask.go

feat
currently not possible to pass non-string input to subtasks
allow to pass a JSON string as input to subtasks

feat(subtask): allow to pass inputs as json

---

engine/engine.go

(fix): Fix iterator to child metadata

---

api/api_test.go
engine/engine.go
engine/engine_test.go
engine/step/step.go
models/task/task.go
models/tasktemplate/fromdir_test.go
pkg/taskutils/taskutils.go
ui/dashboard/package-lock.json
ui/dashboard/package.json
ui/dashboard/projects/utask-lib/src/lib/@components/task-status/task-status.sass
ui/dashboard/projects/utask-lib/src/lib/@models/task.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/stats/stats.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass
ui/dashboard/projects/utask-lib/src/lib/@routes/tasks/tasks.html
ui/dashboard/projects/utask-lib/src/lib/@services/workflow.service.ts

Display improvement.
Delayed tasks appear with the TODO state.
Delayed tasks appear with the DELAYED new state.
NA.
NA

(feat): Add a custom label for delayed tasks

---

go.mod
go.sum
ui/dashboard/package-lock.json
ui/dashboard/package.json

chore(deps): bump dependencies

---

vscode/CHANGELOG.md

chore(vscode): bump to version 1.6.0

---

hack/template-schema.json
pkg/plugins/builtin/ssh/README.md
pkg/plugins/builtin/ssh/ssh.go

Feature
Add `timeout` to SSH plugin
No
Closes #209

feat(ssh): add timeout support for SSH plugin

---

pkg/notify/init/init.go
pkg/notify/messages.go
utask.go

Add a failure_or_done notification strategy

Add failure_or_done notification stragegy

---

pkg/taskutils/taskutils.go

Add resolution id on the task creation
No resolution ID on the task creation output
The resolution ID on the task creation output
No
/

feat(taskutils): add resolution id on the task creation

---

ui/dashboard/projects/utask-lib/src/lib/@models/template.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html

feat(start_over): increase visibility of 'Start Over' button

---

ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html

feat(ui): disable button if not available in task-viewer

---

Makefile
api/metrics.go
models/task/stats.go
models/task/stats_test.go

feat(metrics): add template name as label for utask_task_state telemetry

---

api/handler/resolution.go

fix(resolution): release Lock

---

README.md
engine/engine.go
engine/values/values.go

Feature: adds 2 new templating values: max_retries and try_count
They do not exist
Values are available
No

adds max_retries and try_count to the templating values available

---

ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts

fix(dashboard): allow to edit TODO tasks

---

ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.component.ts

fix(ui): allow admin to edit requests

---

ui/dashboard/projects/utask-lib/src/lib/@models/resolution.model.ts
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.html
ui/dashboard/projects/utask-lib/src/lib/@routes/task/task.sass

feat(dashboard): display the resolver_inputs

---

hack/template-schema.json

Fix JSON schema after #474 and #475 
Missing `final` and `foreach` step condition properties
`final` and `foreach` step condition properties are now taken into account
No
x

Json schema

---

engine/engine.go

Bug fix
For loop do not capture anymore the variable
No
Resolves #480

fix: capture step correctly into loop

---

api/bind.go
engine/engine_test.go
engine/functions/functions.go
models/tasktemplate/fromdir.go
models/tasktemplate/fromdir_test.go
pkg/notify/webhook/webhook.go
pkg/plugins/builtin/http/http.go
pkg/plugins/builtin/http/http_test.go
pkg/plugins/builtin/httputil/httputil.go
pkg/plugins/builtin/httputil/httputil_test.go
pkg/plugins/plugins.go

chore: remove refs to deprecated io/ioutil

---

ui/dashboard/package-lock.json
ui/dashboard/package.json
ui/dashboard/projects/utask-lib/src/lib/@components/error-message/error-message.component.ts

Fix the error message component display
Some generic HTTP error message were used when the response body is in YAML
- Fix the high severity vulnerability from `npm audit`

Fix the error message component display when the error response format is YAML

---

vscode/CHANGELOG.md

chore: bump v1.30

---

go.mod
go.sum

chore: upgrade otto library

---

engine/step/step.go

Bug fix.
Steps' conditions are evaluated even though the step isn't in a final state. See #499.
Steps' conditions evaluation is also prevented when the step is in the WAITING, RUNNING or TO_RETRY state.
No.

fix(step): Prevented step's conditions from being evaluated when the step isn't in a final state

---

vscode/CHANGELOG.md

chore(vscode): bump version

---

pkg/plugins/builtin/apiovh/apiovh.go

Bug fix
Cannot use µTask specific templating inside apiovh credentials
We can
No

fix: apiovh: allow µTask specific templating inside credentials

---

vscode/package.json
vscode/web/package-lock.json
vscode/web/package.json

fix(vscode): build

---

engine/step/stepcondition.go

Bug fix
Error message obsfuscated
Error message visible
NO
Do it

fix: forward error message when function is not existing
